-- MySQL Script generated by MySQL Workbench
-- Wed Jul 22 10:58:02 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ecofactory_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ecofactory_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ecofactory_db` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ;
-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8mb3 ;
USE `ecofactory_db` ;

-- -----------------------------------------------------
-- Table `ecofactory_db`.`maquinas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecofactory_db`.`maquinas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `setor` VARCHAR(100) NULL DEFAULT 'Geral',
  `status` ENUM('online', 'aguardando', 'atencao', 'offline') NULL DEFAULT 'online',
  `temperatura` INT NULL DEFAULT '0',
  `carga` INT NULL DEFAULT '0',
  `criado_em` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ecofactory_db`.`atividades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecofactory_db`.`atividades` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `maquina_id` INT NOT NULL,
  `mensagem` VARCHAR(255) NOT NULL,
  `criado_em` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `maquina_id` (`maquina_id` ASC) VISIBLE,
  CONSTRAINT `atividades_ibfk_1`
    FOREIGN KEY (`maquina_id`)
    REFERENCES `ecofactory_db`.`maquinas` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ecofactory_db`.`configuracoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecofactory_db`.`configuracoes` (
  `id` INT NOT NULL DEFAULT '1',
  `nome_empresa` VARCHAR(100) NULL DEFAULT 'EcoFactory OS',
  `temp_limite_alerta` INT NULL DEFAULT '80',
  `notificacoes_email` TINYINT(1) NULL DEFAULT '1',
  `email_alerta` VARCHAR(150) NULL DEFAULT 'admin@empresa.com',
  `modo_manutencao` TINYINT(1) NULL DEFAULT '0',
  `atualizado_em` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ecofactory_db`.`ocorrencias_sst`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecofactory_db`.`ocorrencias_sst` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `maquina_id` INT NOT NULL,
  `titulo` VARCHAR(150) NOT NULL,
  `gravidade` VARCHAR(20) NULL DEFAULT 'Média',
  `descricao` TEXT NULL DEFAULT NULL,
  `criado_em` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id` (`id` ASC) VISIBLE,
  INDEX `fk_sst_maquina` (`maquina_id` ASC) VISIBLE,
  CONSTRAINT `fk_sst_maquina`
    FOREIGN KEY (`maquina_id`)
    REFERENCES `ecofactory_db`.`maquinas` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`resgistro_pets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`resgistro_pets` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `pet_id` INT NOT NULL,
  `quantidade` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`pets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pets` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(50) NOT NULL,
  `porte` VARCHAR(20) NOT NULL,
  `idade` INT NOT NULL,
  `resgistro_pets_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_pets_resgistro_pets_idx` (`resgistro_pets_id` ASC) VISIBLE,
  CONSTRAINT `fk_pets_resgistro_pets`
    FOREIGN KEY (`resgistro_pets_id`)
    REFERENCES `mydb`.`resgistro_pets` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
