-- MySQL Script generated by MySQL Workbench
-- Wed Aug  5 08:20:59 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema ecofactory_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ecofactory_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ecofactory_db` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ;
USE `ecofactory_db` ;

-- -----------------------------------------------------
-- Table `ecofactory_db`.`maquinas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecofactory_db`.`maquinas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `setor` VARCHAR(100) NOT NULL DEFAULT 'Geral',
  `status` ENUM('online', 'aguardando', 'atencao', 'offline') NOT NULL DEFAULT 'online',
  `temperatura` INT NOT NULL DEFAULT '0',
  `carga` INT NOT NULL DEFAULT '0',
  `consumo` INT NOT NULL DEFAULT '120',
  `criado_em` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `ecofactory_db`.`atividades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecofactory_db`.`atividades` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `maquina_id` INT NOT NULL,
  `mensagem` VARCHAR(255) NOT NULL,
  `criado_em` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `maquina_id` (`maquina_id` ASC) VISIBLE,
  CONSTRAINT `atividades_ibfk_1`
    FOREIGN KEY (`maquina_id`)
    REFERENCES `ecofactory_db`.`maquinas` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ecofactory_db`.`configuracoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecofactory_db`.`configuracoes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `temp_limite_critico` INT NOT NULL DEFAULT '70',
  `notif_email_status` ENUM('ativado', 'todas', 'desativado') NOT NULL DEFAULT 'ativado',
  `intervalo_sensores_seg` INT NOT NULL DEFAULT '15',
  `atualizado_em` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `ecofactory_db`.`ocorrencias_sst`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecofactory_db`.`ocorrencias_sst` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(255) NOT NULL,
  `setor` VARCHAR(100) NOT NULL,
  `risco` ENUM('Baixo', 'Médio', 'Alto', 'Crítico') NOT NULL DEFAULT 'Baixo',
  `status` ENUM('Pendente', 'Em Análise', 'Resolvido') NOT NULL DEFAULT 'Pendente',
  `data_registro` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `ecofactory_db`.`producao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecofactory_db`.`producao` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `produto` VARCHAR(150) NOT NULL,
  `maquina_id` INT NULL DEFAULT NULL,
  `maquina_nome` VARCHAR(100) NOT NULL,
  `esperada` INT NOT NULL,
  `realizada` INT NOT NULL,
  `produtividade` DECIMAL(5,2) GENERATED ALWAYS AS (((`realizada` / `esperada`) * 100)) STORED,
  `criado_em` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_producao_maquinas` (`maquina_id` ASC) VISIBLE,
  CONSTRAINT `fk_producao_maquinas`
    FOREIGN KEY (`maquina_id`)
    REFERENCES `ecofactory_db`.`maquinas` (`id`)
    ON DELETE SET NULL)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `ecofactory_db`.`relatorios_sustentabilidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecofactory_db`.`relatorios_sustentabilidade` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `setor` VARCHAR(100) NOT NULL,
  `consumo_energia_kwh` DECIMAL(10,2) NOT NULL DEFAULT '0.00',
  `consumo_agua_m3` DECIMAL(10,2) NOT NULL DEFAULT '0.00',
  `residuos_reciclados_kg` DECIMAL(10,2) NOT NULL DEFAULT '0.00',
  `eficiencia_energetica` DECIMAL(5,2) NOT NULL DEFAULT '0.00',
  `status_ambiental` ENUM('Excelente', 'Bom', 'Atenção', 'Crítico') NOT NULL DEFAULT 'Bom',
  `data_registro` DATE NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `ecofactory_db`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecofactory_db`.`usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  `foto` LONGTEXT NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email` (`email` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
